### PR TITLE
Fix vulnerabilities

### PR DESCRIPTION
**Pull request by buresmi7**

### CODE REVIEW

**Comment by Vadorequest** [comment]
Hi @buresmi7 , thanks for the PR.

I haven't received any vulnerability warning for the `coveralls` package. But it looks like there is a vulnerability indeed. https://snyk.io/vuln/npm:coveralls

I just took a look at the actual usage of `coveralls` and couldn't find any. I'm thinking about removing the library completely from package.json. (maybe it's something that was useful at some point by the main author before we forked it, but it seems unused now). What do you think?

**Comment by buresmi7** [comment]
Yes, I think the best way is remove `coveralls`. Should I remove it in this merge request?

**Comment by Vadorequest** [comment]
I'll take care of it, thanks for helping!

**Comment by Vadorequest** [comment]
Fixed through https://github.com/UnlyEd/serverless-env-copy-plugin/pull/5

I also integrated Snyk badge to the readme, thank you!

**Comment by Vadorequest** [comment]
@buresmi7 v1.0.4 is released on npm 🎉

**Pull request closed without merging**
